# Site settings
title: Xiyuan Zhang
name: Xiyuan Zhang
email: 2022010906019@std.uestc.edu.cn
description: >- # this means to ignore newlines until "baseurl:"
  [cite_start]Undergraduate student in Electronic Information Engineering at the University of Electronic Science and Technology of China (UESTC). [cite: 13]
  Research interests in flexible electronics, machine learning, and neuromorphic computing.

# Footer settings
footer_links:
  - title: Email
    url: mailto:2022010906019@std.uestc.edu.cn
    icon: fas fa-envelope

# For the avatar image, place your photo in /images/ and update the path
avatar: "/images/Xiyuan_Zhang_photo.jpg" # Assumes you have saved your photo here
